---

- name: Ensure the ports that are required by the Red Hat High Availability Add-On are open
  firewalld:
    service: high-availability
    permanent: yes
    state: enabled
  when: sap_hana_ha_pacemaker_configure_firewall

- name: Ensure password for hacluster is configured
  user:
    name: hacluster
    password: "{{ sap_hana_ha_pacemaker_hacluster_password | password_hash('sha512') }}"

- name: Ensure pcsd service is enabled
  systemd:
    name: pcsd.service
    state: started
    enabled: yes

- name: Ensure both Nodes are added to /etc/hosts for heartbeat traffic
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  loop:
    - "{{ sap_hana_ha_pacemaker_node1_ip }}  {{ sap_hana_ha_pacemaker_node1_fqdn }}"
    - "{{ sap_hana_ha_pacemaker_node2_ip }}  {{ sap_hana_ha_pacemaker_node2_fqdn }}"

- name: Authenticate the cluster Nodes
  command: |
    pcs {{ _subject }} auth {{ _auth }} \
    {{ sap_hana_ha_pacemaker_node1_fqdn }} {{ sap_hana_ha_pacemaker_node2_fqdn }} \
    -u hacluster -p {{ sap_hana_ha_pacemaker_hacluster_password }}
  register: auth_cluster
  changed_when: "'Authorized' in auth_cluster.stdout"
  vars:
    _subject: "{{ 'cluster' if ansible_facts['distribution_major_version'] | int == 7 else 'host' }}"
    _auth: "{{ '--auth' if ansible_facts['distribution_major_version'] | int == 7 else '' }}"

- name: Create RHEL HA Cluster
  command: |
    pcs cluster setup {{ _name }} {{ sap_hana_ha_pacemaker_cluster_name }} \
    {{ sap_hana_ha_pacemaker_node1_fqdn }} \
    {{ sap_hana_ha_pacemaker_node2_fqdn }} \
  register: create_cluster
  changed_when: "'Cluster has been successfully set up' in create_cluster.stdout"
  vars:
    _name: "{{ '--name' if ansible_facts['distribution_major_version'] | int == 7 else '' }}"
  run_once: true

- name: Enable the RHEL HA Cluster
  command: pcs cluster enable --all
  register: enable_cluster
  changed_when: "'Cluster Enabled' in enable_cluster.stdout"
  run_once: true

  #did  systemd delay slow this down so it failed? Added timeouts
- name: Start the RHEL HA Cluster
  command: pcs cluster start --all --wait=600 --request-timeout=600
  register: start_cluster
  changed_when: "'Starting Cluster' in start_cluster.stdout"
  run_once: true

- name: Set quorum votes
  command: pcs quorum expected-votes 2
  run_once: true

- name: Configure second link
  command: pcs cluster link add {{ sap_hana_ha_pacemaker_node1_fqdn }}={{ sap_hana_ha_pacemaker_node1_link2_ip }} {{ sap_hana_ha_pacemaker_node2_fqdn }}={{ sap_hana_ha_pacemaker_node2_link2_ip }} options linknumber=2
  run_once: true
  when: sap_hana_ha_pacemaker_node1_link2_ip is defined and sap_hana_ha_pacemaker_node2_link2_ip is defined


# For fenced nodes, they can come up too quickly, and like a zombie, be double tapped by pacemaker
#   This delay might not be needed on less than super fast environments, but for now, is "always"
#     TODO: Make this startup delay optional
# Note: We enable this *after* the initial cluster setup/start, so we don't need to to have ansible know how to
# wait on the initial, one time, startup.
- name: Ensure /etc/systemd/system/corosync.service.d directory exists
  file:
    path: /etc/systemd/system/corosync.service.d
    owner: root
    group: root
    state: directory
    mode: '0755'
  when: sap_hana_ha_pacemaker_startup_delay > 0

- name:  Setup /etc/systemd/system/corosync.service.d/override.conf
  blockinfile:
    owner: root
    group: root
    mode:  '0644'
    create: yes
    path: "/etc/systemd/system/corosync.service.d/override.conf"
    block: |
      [Service]
      ExecStartPre=/bin/sleep 60
  when: sap_hana_ha_pacemaker_startup_delay > 0
